const res=()=>typeof GetParentResourceName==='function'?GetParentResourceName():'qb-marketplace-community';const $=s=>document.querySelector(s);const state={open:false,config:{},inventory:[],offers:[],myOffers:[],sales:[],pending:0,drafts:[],busy:false,tab:'sell'};
const post=(name,data={})=>fetch(`https://${res()}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(r=>r.json());
const money=n=>`$${Number(n||0).toLocaleString()}`;const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(m){const t=$('#toast'),d=document.createElement('div');d.textContent=m;t.appendChild(d);setTimeout(()=>d.remove(),3200)}
function img(name,image){return `${state.config.itemImagesPath||''}${image||name+'.png'}`}
function empty(m){return `<div class="empty">${esc(m)}</div>`}
function switchTab(tab){state.tab=tab;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===tab));if(tab==='offers')refreshOffers();if(tab==='mine')refreshMyOffers();if(tab==='history')refreshHistory()}
function renderInventory(){const q=$('#inventorySearch').value.toLowerCase();const rows=state.inventory.filter(i=>(i.label+i.name).toLowerCase().includes(q));$('#inventory').innerHTML=rows.length?rows.map(i=>`<article class="item"><img src="${img(i.name,i.image)}"><div><b>${esc(i.label)}</b><div class="meta">${esc(i.name)} · x${i.amount} · ${i.weight||0}g</div></div><div class="row"><input class="mini qty" min="1" max="${i.amount}" type="number" value="1"><input class="mini price" min="${state.config.minPrice||1}" type="number" placeholder="Prix"><button class="btn add" data-name="${esc(i.name)}">Ajouter</button></div></article>`).join(''):empty('Aucun item vendable.');}
function renderDrafts(){const el=$('#drafts');el.innerHTML=state.drafts.length?state.drafts.map((d,i)=>`<article class="offer"><div class="row"><b>${esc(d.label)}</b><button class="btn rm" data-i="${i}">Retirer</button></div><div class="meta">${esc(d.name)} · x${d.quantity}</div><div class="price">${money(d.price)} / unité</div></article>`).join(''):empty('Ajoutez des items avant de confirmer.');}
function renderOffers(){const q=$('#offersSearch').value.toLowerCase(),sort=$('#offerSort').value;let rows=state.offers.filter(o=>(o.item_label+o.item_name).toLowerCase().includes(q));rows.sort((a,b)=>sort==='priceAsc'?a.price-b.price:sort==='priceDesc'?b.price-a.price:new Date(b.created_at)-new Date(a.created_at));$('#offersList').innerHTML=rows.length?rows.map(o=>card(o,true)).join(''):empty('Aucune offre disponible.');}
function renderMine(){ $('#myOffers').innerHTML=state.myOffers.length?state.myOffers.map(o=>card(o,false)).join(''):empty('Vous n’avez aucune offre active.');}
function renderHistory(){ $('#pending').textContent=money(state.pending); $('#sales').innerHTML=state.sales.length?state.sales.map(s=>`<article class="sale"><div class="row"><b>${esc(s.item_label)}</b><span>${esc(s.created_at||'')}</span></div><div class="meta">x${s.quantity} · ${money(s.unit_price)} / unité · ${s.withdrawn?'retiré':'en attente'}</div><div class="price">${money(s.total_price)}</div></article>`).join(''):empty('Aucune vente enregistrée.');}
function card(o,buy){return `<article class="offer"><div class="row"><b>${esc(o.item_label)}</b><span class="meta">#${o.id}</span></div><div class="meta">${esc(o.item_name)} · stock x${o.quantity}${o.seller_name?' · '+esc(o.seller_name):''}</div><div class="price">${money(o.price)}</div><div class="meta">Créée: ${esc(o.created_at||'')} ${o.expires_at?'· Expire: '+esc(o.expires_at):''}</div>${buy?`<div class="row"><input class="mini buyQty" min="1" max="${o.quantity}" type="number" value="1"><button class="btn primary buy" data-id="${o.id}">Acheter</button><button class="btn buyAll" data-id="${o.id}" data-q="${o.quantity}">Tout</button></div>`:`<button class="btn cancel" data-id="${o.id}">Annuler et récupérer</button>`}</article>`}
async function loadInitial(){const r=await post('getInitialData');if(!r.ok)return toast(r.message||'Erreur');state.inventory=r.data.inventory||[];state.offers=r.data.offers||[];state.myOffers=r.data.myOffers||[];state.sales=r.data.sales||[];state.pending=r.data.pendingEarnings||0;renderAll()}
function renderAll(){renderInventory();renderDrafts();renderOffers();renderMine();renderHistory()}
async function refreshOffers(){const r=await post('refreshOffers');if(r.ok){state.offers=r.data||[];renderOffers()}}
async function refreshMyOffers(){const r=await post('refreshMyOffers');if(r.ok){state.myOffers=r.data||[];renderMine()}}
async function refreshHistory(){const r=await post('refreshHistory');if(r.ok){state.sales=r.data.sales||[];state.pending=r.data.pendingEarnings||0;renderHistory()}}
async function action(name,data,after){if(state.busy)return;state.busy=true;try{const r=await post(name,data);toast(r.message||'OK');if(r.ok&&after)await after()}finally{state.busy=false}}
window.addEventListener('message',e=>{if(e.data.action==='open'){state.config=e.data.config||{};$('#title').textContent=state.config.title||'Marketplace';$('#app').classList.remove('hidden');loadInitial()}if(e.data.action==='close')$('#app').classList.add('hidden');if(e.data.action==='refresh')loadInitial();if(e.data.action==='toast')toast(e.data.message)});
document.addEventListener('keydown',e=>{if(e.key==='Escape')post('close')});$('#close').onclick=()=>post('close');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));['inventorySearch','offersSearch'].forEach(id=>$('#'+id).oninput=()=>id==='inventorySearch'?renderInventory():renderOffers());$('#offerSort').onchange=renderOffers;
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.classList.contains('add')){const item=state.inventory.find(i=>i.name===b.dataset.name),row=b.closest('.item'),q=+row.querySelector('.qty').value,p=+row.querySelector('.price').value;if(!item||q<1||q>item.amount||p<1)return toast('Quantité ou prix invalide');state.drafts.push({name:item.name,label:item.label,quantity:q,price:p,metadata:item.metadata||{}});renderDrafts()}if(b.classList.contains('rm')){state.drafts.splice(+b.dataset.i,1);renderDrafts()}if(b.id==='confirmListings')action('createListings',{listings:state.drafts},async()=>{state.drafts=[];await loadInitial()});if(b.classList.contains('buy'))action('buyOffer',{offerId:+b.dataset.id,quantity:+b.closest('.offer').querySelector('.buyQty').value},loadInitial);if(b.classList.contains('buyAll'))action('buyOffer',{offerId:+b.dataset.id,quantity:+b.dataset.q},loadInitial);if(b.classList.contains('cancel'))action('cancelOffer',{offerId:+b.dataset.id},loadInitial);if(b.id==='withdraw')action('withdrawEarnings',{},refreshHistory)});
