CREATE TABLE IF NOT EXISTS `marketplace_listings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `seller_citizenid` VARCHAR(64) NOT NULL,
  `seller_name` VARCHAR(96) NOT NULL,
  `item_name` VARCHAR(80) NOT NULL,
  `item_label` VARCHAR(120) NOT NULL,
  `item_image` VARCHAR(255) DEFAULT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `rarity` VARCHAR(32) DEFAULT 'common',
  `category` VARCHAR(64) DEFAULT 'misc',
  `status` ENUM('active', 'sold', 'cancelled', 'expired') NOT NULL DEFAULT 'active',
  `expires_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_marketplace_status_expires` (`status`, `expires_at`),
  KEY `idx_marketplace_seller_status` (`seller_citizenid`, `status`),
  KEY `idx_marketplace_item_status` (`item_name`, `status`),
  KEY `idx_marketplace_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `marketplace_sales` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `listing_id` INT UNSIGNED NOT NULL,
  `seller_citizenid` VARCHAR(64) NOT NULL,
  `buyer_citizenid` VARCHAR(64) NOT NULL,
  `item_name` VARCHAR(80) NOT NULL,
  `item_label` VARCHAR(120) NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `unit_price` INT UNSIGNED NOT NULL,
  `gross_amount` INT UNSIGNED NOT NULL,
  `tax_amount` INT UNSIGNED NOT NULL DEFAULT 0,
  `net_amount` INT UNSIGNED NOT NULL,
  `seller_name` VARCHAR(96) NOT NULL,
  `buyer_name` VARCHAR(96) NOT NULL,
  `withdrawn` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `withdrawn_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_marketplace_sales_seller_withdrawn` (`seller_citizenid`, `withdrawn`),
  KEY `idx_marketplace_sales_buyer` (`buyer_citizenid`),
  KEY `idx_marketplace_sales_listing` (`listing_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
